### ISSUE TITLE
ArgumentOutOfRange Exception using AsQueryable().ToList()

### ISSUE THREAD

**Issue by alexjamesbrown** [atheken/NoRM#43]
I'm trying to do the following:

```
            var collection = m.GetCollection<Post>()
                .AsQueryable().ToList();
```

However, this throws an ArgumentOutOfRangeException:
Non-negative number required.
Parameter name: count

Am I doing something wrong...?

Stack Trace:

   at Norm.BSON.BsonDeserializer.Deserialize[T](BinaryReader stream, Int32 length) in C:\Users\alexb\Downloads\atheken-NoRM-v0.9.8-4-gd8faa81\atheken-NoRM-d8faa81\NoRM\BSON\BsonDeserializer.cs:line 102
   at Norm.BSON.BsonDeserializer.Deserialize[T](Int32 length, BinaryReader reader, IDictionary`2& outProps) in C:\Users\alexb\Downloads\atheken-NoRM-v0.9.8-4-gd8faa81\atheken-NoRM-d8faa81\NoRM\BSON\BsonDeserializer.cs:line 76
   at Norm.Protocol.Messages.ReplyMessage`1..ctor(IConnection connection, String fullyQualifiedCollestionName, BinaryReader reply, MongoOp originalOperation, Int32 limit) in C:\Users\alexb\Downloads\atheken-NoRM-v0.9.8-4-gd8faa81\atheken-NoRM-d8faa81\NoRM\Protocol\Messages\ReplyMessage.cs:line 60
   at Norm.Protocol.Messages.QueryMessage`2.Execute() in C:\Users\alexb\Downloads\atheken-NoRM-v0.9.8-4-gd8faa81\atheken-NoRM-d8faa81\NoRM\Protocol\Messages\QueryMessageGeneric.cs:line 119
   at Norm.MongoQueryExecutor`3.<GetEnumerator>d__0.MoveNext() in C:\Users\alexb\Downloads\atheken-NoRM-v0.9.8-4-gd8faa81\atheken-NoRM-d8faa81\NoRM\MongoQueryExecutor.cs:line 74
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MongoTest.Program.justGetTitles() in C:\Users\alexb\Desktop\New folder\MongoTest\MongoTest\Program.cs:line 112
   at MongoTest.Program.Main(String[] args) in C:\Users\alexb\Desktop\New folder\MongoTest\MongoTest\Program.cs:line 27
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by atheken** [comment]
Will investigate

**Comment by alexjamesbrown** [comment]
I deleted the collection, and started it again, and i can't seem to reproduce the error (it works fine now)

I'd love to know what went wrong!

**Comment by atheken** [comment]
Hmm, that's still worrisome, but thanks for the update.

**Comment by joelvh** [comment]
I've run into this error as well, but the original exception is at BsonDeserializer line 503 in ReadString():

502: var length = _reader.ReadInt32();
503: var buffer = _reader.ReadBytes(length - 1); //todo: again, look at fragementation prevention

Line 502 results in a negative number (negative thousands).  The property deserializer._current.Digested is larger than deserializer._current.Length.  The Digest property keeps growing for several iterations before ReadString() is called.

When this exception is caught, the catch block throws the additional exception already mentioned above, by subtracting deserializer._current.Digested from deserializer._current.Length to do a final read on line 101.  This results in a negative number.  The exception mentioned above is masking the original.

I will try to do some more debugging, but this BsonDeserializer is not very easy to follow!  If someone else can take a look, I have the "bad" data in a MongoHQ database.

Any thoughts?  Thanks!

**Comment by joelvh** [comment]
I noticed that after deserializing an array, the next string value parsed has this character sequence (ASCII decimal values), where the second-to-last character is a "U":

2 48 0 1 0 0 0 0 0 0 2 85 3

Then a string property (called "Url") is deserialized , but only the value is retrieved.  The "U" from the property name seems to be truncated in the sequence above.  Then it's followed by a string consisting of this character sequence:

3 0 0 0 0 0 0 0 0 0 0 0 0 0 0

Then the index is out of range on line 503 and we get the exception.

I'm not that familiar with binary serialization, and what these characters might be delimiting or if they are somehow garbage.

**Comment by joelvh** [comment]
I figured out the issue.  NoRM does not handle updates and modifiers extensively enough.  (I ran into this issue with creating aliases too.)

My document looks like this, which is derived from my .NET class that defines Tags as a string array:

{ Tags: [ ... ] }

I ran an update using the AddToSet modifier, specifying an array of new tags to add.  I assumed NoRM would merge the arrays or throw an error if I had to specify individual strings in AddToSet instead.  However, the array was added as a value inside the Tags array, resulting in a nested array.

{ Tags: [ [""] ] }

The deserializer thinks the value inside the Tags array will be a string because that is what the .NET property on my class defines, but the value retrieved from MongoDB is actually an array.  Therefore it's screwing up deserializing everything following this value.

Database updates are made using anonymous classes, so the update routines in NoRM are not accessing the proper .NET class type to to retrieve properties from.  Therefore, there is no validation that the values specified for a property are compatible with the .NET class originally serialized (saved) to the database.

This is the same reason that aliases don't work.  Because the class type used to access properties and alias mappings is the anonymous type used to specify Update criteria.

**Comment by joelvh** [comment]
As a follow-up, NoRM gets the itemType for a generic list in BsonDeserializer.ReadList() on line 388:

388: var itemType = ListHelper.GetListItemType(listType);

Because NoRM update commands don't verify types properly, data can become corrupted, such as a string array containing a nested array instead of a string value (e.g. { Tags: [ "tag1", [ "tag2", "tag3"] ] } instead of { Tags: [ "tag1", "tag2", "tag3" ] } ).

Deserializing will get the storageType of the next object in the array on line 394:

394: var storageType = ReadType();

This will be an array instead of a string for the second value in my Tags array.  However, the storageType is not validated against the itemType, so it deserializes the array as a string.

TODO:  Need to check storageType == itemType.

DeserializeValueAfterConversion(type, storedType) tests type == typeof(string) and subsequently calling ReadString(), when the storageType == BSONTypes.Array.
